# Generated by Django 4.1.7 on 2023-04-20 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_alter_profile_fullname_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=19, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator('^\\d+$')])),
                ('name', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^\\d+$')])),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^\\d+$')])),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^\\d+$')])),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
