# Generated by Django 4.1.7 on 2023-04-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sales_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='product',
            field=models.ManyToManyField(related_name='specifications', to='api.product'),
        ),
    ]
