# Generated by Django 4.1.7 on 2023-04-25 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_baskets_product_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('deliveryType', models.CharField(max_length=30)),
                ('paymentType', models.CharField(max_length=30)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('href', models.SlugField()),
                ('freeDelivery', models.BooleanField()),
                ('images', models.JSONField()),
                ('tags', models.JSONField()),
                ('reviews', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
